name: "CI"

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  GO_VERSION: 1.18

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Branch name
        run: echo "running on branch ${{ steps.branch-name.outputs.current_branch }}"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: go install ./...
      - name: Check tests
        run: make tests

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "running on branch ${{ steps.branch-name.outputs.current_branch }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true
